-- If you copy YCC PROD schema & data to YCC TEST, the sequence might be out of place.
-- This can fix it. Only intended for TEST.

ALTER TABLE helper_tasks MODIFY id NUMBER GENERATED BY DEFAULT AS IDENTITY(START with 10000 INCREMENT by 1) NOT NULL;
